name: Node.js Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t nodeapp .

      - name: Run Docker Container
        run: docker run -d --name myapp_container nodeapp

      - name: Test Application
        run: docker exec myapp_container npm test

      - name: Cleanup
        run: docker stop myapp_container && docker rm myapp_container
